#!/bin/bash

# Default relative path to the scripts directory
SCRIPT_DIR="$(dirname "$0")/src"

execute_script() {
    script_path="$SCRIPT_DIR/$1"
    if [ -f "$script_path" ] && [ -x "$script_path" ]; then
        echo "Executing $script_path..."
        "$script_path"
    else
        echo "Script $script_path not found or not executable."
    fi
}

case "$1" in
    --setup)
        execute_script "ore_setup.sh"
        ;;
    --update-urls)
        execute_script "update_urls.sh"
        ;;
    --sol-balance|-s)
        execute_script "check_sol_balance.sh"
        ;;
    --fund-sol|-f)
        execute_script "fund_sol.sh"
        ;;
    --rewards)
        execute_script "check_ore_rewards.sh"
        ;;
    --claim)
        execute_script "claim_ore_batch.sh"
        ;;
    --ore-balance|-o)
        execute_script "check_ore_balance.sh"
        ;;
    --start-miners|-m)
        execute_script "start_miners.sh"
        ;;
    --pubkeys)
        execute_script "fetch_pubkey.sh"
        ;;
    --version|-v)
        echo "Version 0.0.6"
        ;;
    --help|-h)
        echo "Usage: $0 COMMAND"
        echo "Commands:"
        echo "  --setup             Initialize and configure wallets and mining scripts."
        echo "  --update-urls       Update the RPC URLs in the ORE scripts."
        echo "  -s, --sol-balance   Check the SOL balance for each address."
        echo "  -f, --fund-sol      Fund each address with SOL to meet the minimum balance."
        echo "  --rewards           Check the ORE rewards for each address."
        echo "  --claim             Automate claiming ORE rewards for configured wallets."
        echo "  -o, --ore-balance   Check the ORE balance for each address."
        echo "  -m, --start-miners  Start multiple screens for ORE mining sessions."
        echo "  --pubkeys           Fetch the public keys for each address and export to addr_list.txt."
        echo "  -v, --version       Display the version of the script."
        echo ""
        echo "Example:"
        echo "  $0 --setup          Initialize and configure wallets and mining scripts."
        echo "  $0 --sol-balance    Checks the SOL balance for addresses in addr_list.txt."
        ;;
    *)
        echo "Usage: $0 COMMAND"
        echo "Try '$0 --help' or '$0 -h' for more information."
        exit 1
        ;;
esac
