#!/bin/bash

# Default relative path to the scripts directory
SCRIPT_DIR="$(dirname "$0")/src"

# Default version of the project
version="2.0.0 (beta)"

# Function to execute a script from the src directory
execute_script() {
    script_path="$SCRIPT_DIR/$1"
    shift
    if [ -f "$script_path" ] && [ -x "$script_path" ]; then
        echo "Executing $script_path $@"
        "$script_path" "$@"
    else
        echo "Script $script_path not found or not executable."
    fi
}

# Function to print the help message
print_help_message() {
    echo "Usage: $0 COMMAND"
    echo "Commands:"
    echo "  --setup             Initialize and configure wallets and mining scripts."
    echo "  -u, --update-urls   Update the RPC URLs in the ORE scripts."
    echo "  -s, --sol-balance   Check the SOL balance for each address."
    echo "  -f, --fund-sol      Fund each address with SOL to meet the minimum balance."
    echo "  -r, --rewards       Check the ORE rewards for each address."
    echo "  -c, --claim         Automate claiming ORE rewards for configured wallets."
    echo "  -o, --ore-balance   Check the ORE balance for each address."
    echo "  -m, --start-miners  Start multiple screens for ORE mining sessions."
    echo "  --pubkeys           Fetch the public keys for each address and export to addr_list.txt."
    echo "  -cs, --collect-sol  Collect SOL from all addresses to a single address."
    # V2 Commands, beta features, please use with caution
    echo "  --upgrade           Upgrade the ORE token to V2 in batches."
    echo "  --stake             Stake ORE tokens in batches."
    # Informational commands
    echo "  -v, --version       Display the version of the script."
    echo ""
    echo "Example:"
    echo "  $0 --setup          Initialize and configure wallets and mining scripts."
    echo "  $0 --sol-balance    Checks the SOL balance for addresses in addr_list.txt."
}

case "$1" in
    --setup)
        execute_script "ore_setup.sh" "${@:2}"
        ;;
    --update-urls|-u)
        execute_script "update_urls.sh" "${@:2}"
        ;;
    --sol-balance|-s)
        execute_script "check_sol_balance.sh" "${@:2}"
        ;;
    --fund-sol|-f)
        execute_script "fund_sol.sh" "${@:2}"
        ;;
    --rewards|-r)
        execute_script "check_ore_rewards.sh" "${@:2}"
        ;;
    --claim|-c)
        execute_script "claim_ore_batch.sh" "${@:2}"
        ;;
    --ore-balance|-o)
        execute_script "check_ore_balance.sh" "${@:2}"
        ;;
    --start-miners|-m)
        execute_script "start_miners.sh" "${@:2}"
        ;;
    --pubkeys)
        execute_script "fetch_pubkeys.sh" "${@:2}"
        ;;
    --collect-sol|-cs)
        execute_script "collect_sol.sh" "${@:2}"
        ;;
    # V2 Commands, beta features, please use with caution
    --upgrade)
        execute_script "v2_upgrade.sh" "${@:2}"
        ;;
    --stake)
        execute_script "v2_stake.sh" "${@:2}"
        ;;
    # Informational commands
    --version|-v)
        echo "Ore-Wizard v$version"
        ;;
    --help|-h)
        print_help_message
        ;;
    *)
        print_help_message
        exit 1
        ;;
esac
